#Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StopWatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StopWatch

  target 'StopWatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StopWatchUITests' do
    # Pods for testing
  end

pod 'Moya', '~> 14.0'
pod 'Charts'
pod 'SwiftyJSON'

end
